export const playstyles = [
    "allroundBrute",
    "allroundShooter",
    "blackCat",
    "blazingAssassin",
    "bombardier",
    "boombasticAssassin",
    "chiropractor",
    "chokeArtist",
    "cleanIcaAssassin",
    "concertPianist",
    "envenomingAssassin",
    "exectrocutingAssassin",
    "expertRifleAssassin",
    "flexibleMurderer",
    "grimReaper",
    "headhunter",
    "henchman",
    "hiredGun",
    "huntsman",
    "immolater",
    "jinx",
    "longarmShooter",
    "marksman",
    "neckbreakingAssassin",
    "necksnapper",
    "nutcracker",
    "phantomIcaAssassin",
    "pianoTuner",
    "pistoleer",
    "professionalIcaAssassin",
    "rifleman",
    "shadowAssassin",
    "sharpshooter",
    "shotgunSpecialist",
    "silentAssassin",
    "skillfullIcaAssassin",
    "sniper",
    "stealthIcaAssassin",
    "tracelessIcaAssassin",
    "trapper",
    "trapsmith",
    "unlucky13",
    "versatileAssassin",
    "virtuosoAssassin",
    "volatileAssassin",
];

export const randomLabel = (t) => {
    const playstyle = playstyles[Math.floor(Math.random() * playstyles.length)];
    return t(`enum.playstyle.${playstyle}`);
}