<?php

enum Mission : string{
    case TRAINING = "training";
    case THE_FINAL_TEST = "the_final_test";
    case THE_SHOWSTOPPER = "the_showstopper";
    case HOLIDAY_HOARDERS = "holiday_hoarders";
    case WORLD_OF_TOMORROW = "world_of_tomorrow";
    case THE_ICON = "the_icon";
    case LANDSLIDE = "landslide";
    case THE_AUTHOR = "the_author";
    case A_GUILDED_CAGE = "a_guilded_cage";
    case A_HOUSE_BUILT_ON_SAND = "a_house_built_on_sand";
    case CLUB_27 = "club_27";
    case THE_SOURCE = "the_source";
    case FREEDOM_FIGHTERS = "freedom_fighters";
    case THE_VECTOR = "the_vector";
    case SITUS_INVERTUS = "situs_invertus";
    case PATIENT_ZERO = "patient_zero";
    case HOKKAIDO_SNOW_FESTIVAL = "hokkaido_snow_festival";
    case NIGHTCALL = "nightcall";
    case THE_FINISH_LINE = "the_finish_line";
    case A_SILVER_TONGUE = "a_silver_tongue";
    case THREE_HEADER_SERPENT = "three_header_serpent";
    case EMBRACE_OF_THE_SERPENT = "embrace_of_the_serpent";
    case CHASING_A_GHOST = "chasing_a_ghost";
    case ILLUSIONS_OF_GRANDEUR = "illusions_of_grandeur";
    case ANOTHER_LIFE = "another_life";
    case A_BITTER_PILL = "a_bitter_pill";
    case THE_ARK_SOCIETY = "the_ark_society";
    case GOLDEN_HANDSHAKE = "golden_handshake";
    case THE_LAST_RESORT = "the_last_resort";
    case THE_LAST_YARDBIRD = "the_last_yardbird";
    case THE_PEN_AND_THE_SWORD = "the_pen_and_the_sword";
    case CRIME_AND_PUNISHMENT = "crime_and_punishment";
    case ON_TOP_OF_THE_WORLD = "on_top_of_the_world";
    case DEATH_IN_THE_FAMILY = "death_in_the_family";
    case THE_DARTMOOR_GARDEN_SHOW = "the_dartmoor_garden_show";
    case APEX_PREDATOR = "apex_predator";
    case END_OF_AN_ERA = "end_of_an_era";
    case THE_FAREWELL = "the_farewell";
    case UNTOUCHABLE = "untouchable";
    case SHADOWS_IN_THE_WATER = "shadows_in_the_water";
}